site_esoterics/blog/urls.py
from django.urls import path
from .views import *
from . import views
urlpatterns = [
    path('', Blog.as_view(), name='blog'),
    path('blog-create/',BlogCreate.as_view()),
]

site_esoterics/contacts/urls.py
from django.urls import path
from .views import *
from . import views
urlpatterns = [
     path('', ContactListView.as_view(), name='contact_view'),
     #path('', contact),
     path("postuser/", views.postuser),
     path("viewContact/", views.view),
]
    

site_esoterics/esoterics/site_esoterics/esoterics/esoterics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('blog/', blog, name='blog'),
    path('price/', price, name='price'),
    path('contacts/', contacts, name='contacts'),
    path('news/', include('news.urls'), name='news'),

]

site_esoterics/esoterics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from userapp.views import RegisterView, LoginView, LogoutView
from price.views import PriceAPIView
from news.views import NewsAPIView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('blog/', include('blog.urls')),
    path('price/',include('price.urls')),
    path('api/v1/price/', PriceAPIView.as_view()),
    path('contacts/', include('contacts.urls')),
    path('news/', include('news.urls')),
    path('register/', RegisterView.as_view(), name='registration'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('api/v1/news/',NewsAPIView.as_view()),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_esoterics/contacts/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    phone = models.ImageField()
    message = models.TextField(max_length=1000)
    time_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # Будет отображаться следующее поле в панели администрирования
        return '{} {} {} {} {}'.format(self.name,self.email ,self.phone,self.message,self.time_create)
    



    

site_esoterics/contacts/views.py
from django.shortcuts import render

from contacts.models import Contact
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.forms import BlogForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
# Create your views here.

from django.http import HttpResponse
import django
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages

class  ContactListView(ListView):
    model = Contact
    
   # template_name = 'contacts/contat_list.html'

# Функция формы обратной связи


def success(request):
    email = request.POST.get('email', '')
    data = """
Hello there!

I wanted to personally write an email in order to welcome you to our platform.\
 We have worked day and night to ensure that you get the best service. I hope \
that you will continue to use our service. We send out a newsletter once a \
week. Make sure that you read it. It is usually very informative.

Cheers!
~ Yasoob
    """
    send_mail('Welcome!', data, "Yasoob",
              [email], fail_silently=False)
    return render(request, 'success.html')



        



def postuser(request):
    # получаем из данных запроса POST отправленные через форму данные
    if request.method == "POST":

        contact = Contact()
        contact.name = request.POST.get("name", "Undefined")
        contact.email = request.POST.get("email", 1)
        contact.phone = request.POST.get("phone", 1)
        contact.message = request.POST.get("message", 1)
            
        contact.save()
        

    '''
     id = request.data['id'],    
    name = request.POST.get("name", "Undefined")
    email = request.POST.get("email", 1)
    phone = request.POST.get("phone", 1)
    message = request.POST.get("message", 1)
    send_mail('Вы отпраили сообщение',[name],[email],[phone],[message])
    contact = Contact()
    
    contact.name = request.POST.get('name')
    contact.email = request.POST.get('email')
    contact.phone = request.POST.get('phone')
    contact.message = request.POST.get('message')
    '''  
    #return HttpResponse(f"<h2>Name: {name}  Age: {email} phone: {phone} message:{message}</h2>")
    return render(request, 'contacts/success.html')



class ContactView(UserPassesTestMixin, ListView):
    model = Contact
    post = Contact.objects.all()
    #template_name = 'smContact.html'
    success_url = 'viewContact/'
    def test_func(self):
        return self.request.user.is_staff
    


def view (request):
    
    contact =  Contact.objects.all()
    print(contact)
    
    return render(request, 'contacts/smContact.html',{'contact':contact})

site_esoterics/contacts/templates/contacts/contact_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'contacts.css' %}">
    <title>Document</title>
</head>
<body>
    
<!--

    <div class="panel panel-success">
        <div class="panel-heading">
          <h2 class="panel-title">Обратная связь</h2>
        </div>
        <div class="panel-body">
      <div class="well well-lg">
          <h3></h3>
      <form action="#" method="post">
          {% csrf_token %}
      {#    {% bootstrap_form form %}#}
          {{ form.non_field_errors }}
          <div>
            <label for="id_subject">Тема:</label>
            {{ form.subject.errors }}
      {#	  {{ form.subject }}#}
            <input class="form-control" id="id_subject" name="subject" placeholder="Тема">
          </div>
          &nbsp;
          <div>
            <label for="id_sender">E-mail:</label>
            {{ form.sender.errors }}
      {#	  {{ form.sender }}#}
            <input class="form-control" id="id_sender" name="sender" placeholder="Ваш e-mail">
          </div>
          &nbsp;
          <div>
            <label for="id_message">Сообщение:</label>
            {{ form.message.errors }}
      {#	  {{ form.message }}#}
            <textarea class="form-control" id="id_message" name="message" placeholder="Введите ваше сообщение"></textarea>
          </div>
          &nbsp;
          <div>
            {{ form.copy.errors }}
            <label for="id_copy">{{ form.copy }} Отправить копию себе </label>
          </div>
          <br>
          <input type="submit" class="btn btn-success" value="Отправить сообщение"/>
      </form>
        </div>
      </div>
      </div>
    -->
    
    
    <!-- Контейнер выравнивает по ширине и по центру -->
    <div style="margin-top: 40px;" class="containers">

        <!-- content содержит содержимое формы -->
        <div class="content">
  
          <!-- Левая колонка: адрес, телефоны, email. Можете добавить свое -->
          <div class="left-side">
            <div class="address details">
  
              <!-- Вместо классов: название шрифтовых иконок (fontawesome.com) -->
              <i class="fas fa-map-marker-alt"></i>
  
              <!-- topic - заголовок, text-one, text-two - текст -->
              <div class="topic">Адрес</div>
              <div class="text-one">г. Москва</div>
              <div class="text-two">Пресненская наб., 8 стр. 1</div>
            </div>
            <div class="phone details">
              <i class="fas fa-phone-alt"></i>
              <div class="topic">Телефон</div>
              <div class="text-one">8-912-49-47-496</div>
              <div class="text-two">8-900-000-00-00</div>
            </div>
            <div class="email details">
              <i class="fas fa-envelope"></i>
              <div class="topic">Email</div>
              <div class="text-one">dublin87@mail.ru</div>
              <div class="text-two">admin@site.com</div>
            </div>
          </div>
  
          <!-- Правая колонка: сама форма -->
          <div class="right-side">
  
            <!-- Заголовок для формы -->
            <div class="topic-text">Отправьте нам сообщение</div>
  
            <!-- Какой-то дополнительный текст -->
            <p>
              Если у вас есть какие-то вопросы или предложения по сотрудничеству -
              заполните форму ниже
            </p>
  
            <!-- Форма обратной связи -->
            <form action="postuser/" method="post">
            {% csrf_token %}
              <!-- Каждый input для выравнивания вкладываем в блок input-box -->
              <div class="input-box">
                <input type="text" placeholder="Ваше имя"  name="name">
              </div>
              <div class="input-box">
                <input type="text" placeholder="Введите email"  name="email">
              </div>
              <div class="input-box">
                <input type="text" placeholder="Введите телефон"  name="phone"">
              </div>
              <div class="input-box message-box">
                <textarea placeholder="Сообщение"  name="message"></textarea>
              </div>
              <div class="button" >
                <input  class="button" type="submit"  />
              </div>
            </form>
          </div>
        </div>
      </div>
      {% if user.is_staff %}
      <a style="margin: 0 auto; display: block ;width: 150px; white-space:nowrap ;margin-top: 40px ;margin-bottom: 50px;" class="btn btn-primary" href="viewContact/"">Посмотреть  контакты</a>
      {% endif %}
      <!-- Подключение шрифтовых иконок, можно получить на fontawesome.com -->
      <script
        src="https://kit.fontawesome.com/fce9a50d02.js"
        crossorigin="anonymous"
      ></script>
</body>
</html>

{% endblock %}

site_esoterics/contacts/templates/contacts/smContact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



{% for item in contact %}

<div class="album py-5 bg-body-tertiary">
  <div class="container">
      <div class="col">
        <div class="card shadow-sm">
          {% if item.img %}
          <img width="800px" src="{{item.img.url}}">
          {% endif %}
          <!-- <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em"></text></svg> -->
          <div class="card-body">
            <h2 style=" white-space: nowrap" class="card-text">{{item.name}}</h2>
            <h2 class="card-text">{{item.email}}</h2>
            <h2 class="card-text">{{item.phone}}</h2>
            <h2 class="card-text">{{item.message}}</h2>
            <h2 class="card-text">{{item.time_create}}</h2>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">


                <!-- <button type="button" class="btn btn-sm btn-outline-secondary">Просмотр</button> -->
                <!-- <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button> -->
              </div>
              <small class="text-body-secondary">{{item.time_update|date:"d-m-Y H:i:s"}}</small>



        </div>
      </div>
    </div>
  </div>
  </div>
  </div>

 {% endfor %}
{%endblock%}

site_esoterics/contacts/templates/contacts/success.html
{% load static  %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="icon" type="image/x-icon" href="{% static 'img/esoteric.ico' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'userapp\userupp.css' %}">    

    {% block title %}
    <title>Esoteric</title>
    {% endblock %}

<nav class="navbar navbar-expand-lg navbar-light background-color">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav nav-pills nav-fill">
        <!--<ul class="nav flex-column"> --- gorizontal navbar --- -->
            <li class="nav-item">
				<a class="nav-item nav-link" aria-current="page" href="{% url 'home' %}">Домашняя страница</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-item nav-link" href="{% url 'news_view' %}">Новости</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-item nav-link" href="{% url 'price_view' %}">Цены</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-item nav-link" href="{% url 'contact_view' %}">Контакты</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-item nav-link" href="{% url 'blog' %}">Разработчики</a>
			  </li>

        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-item nav-link" href="{% url 'logout' %}">Выход</a>
            </li>
      {% else %}
            </li>
            <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'registration' %}">Регистрация</a>
            </li>
            <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'login' %}">Вход</a>
            </li>
      {% endif %}
        </ul>
      </div>

      {% if user.is_authenticated %}
       <div class="Block" style="margin-bottom:25px;">
                <br>Вы авторизованы как: {{user.username}}
        </div>
      {% else %}
        <div class="Block" style="margin-bottom:25px;">
            <br>Вы не авторизованы
       </div>
      {% endif %}
      
    </div>
  </nav>
</head>
<body>
    <div style="margin-top: 30px;" class="wrapper">
        <div class="wraper-contents">
    
            <div  class="meesage"style="height: 100%;">
                <h1>Сообщение успешно отправленно </h1> 
             </div>
    


<div style="margin-top: 65vh;" class=" footer  text-center text-white">
    <!-- Grid container -->
  <div class="container p-4 pb-0">
  <!-- Section: Social media -->
  <section class="mb-4">
  <!-- Facebook -->
  <a
  class="btn text-white btn-floating m-1"
  style="background-color: #3b5998;"
  href="#!"
  role="button"
  ><i class="fab fa-facebook-f"></i
  ></a>
  
  <!-- Twitter -->
  <a
  class="btn text-white btn-floating m-1"
  style="background-color: #55acee;"
  href="#!"
  role="button"
  ><i class="fab fa-twitter"></i
  ></a>
  
  <!-- Google -->
  <a
  class="btn text-white btn-floating m-1"
  style="background-color: #dd4b39;"
  href="#!"
  role="button"
  ><i class="fab fa-google"></i
  ></a>
  
  <!-- Instagram -->
  <a
  class="btn text-white btn-floating m-1"
  style="background-color: #ac2bac;"
  href="#!"
  role="button"
  ><i class="fab fa-instagram"></i
  ></a>
  
  <!-- Linkedin -->
  <a
  class="btn text-white btn-floating m-1"
  style="background-color: #0082ca;"
  href="#!"
  role="button"
  ><i class="fab fa-linkedin-in"></i
  ></a>
  <!-- Github -->
  <a
  class="btn text-white btn-floating m-1"
  style="background-color: #333333;"
  href="#!"
  role="button"
  ><i class="fab fa-github"></i
  ></a>
  </section>
  <!-- Section: Social media -->
  </div>
  <!-- Grid container -->
  
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
  © 2023 Copyright:
  <a class="text-white" href="https://mdbootstrap.com/">Esoteric.com</a>
  </div>
  <!-- Copyright -->
  </div>
  
  


  </body>
  </html> 
  {% endblock %}